[package]
name = "nv-server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
camino = { workspace = true }
clap = { workspace = true }
dropshot = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
which = { workspace = true }
xshell = { workspace = true }

nv-server-api = { path = "../nv-server-api" }
