[package]
name = "nv-server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
camino.workspace = true
clap.workspace = true
dropshot.workspace = true
itertools.workspace = true
nv-server-api.workspace = true
migration.workspace = true
sea-orm.workspace = true
secrecy.workspace = true
slog.workspace = true
spookey.workspace = true
tokio.workspace = true
workspace-hack.workspace = true
