[package]
name = "nv-common"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
camino.workspace = true
clap-verbosity-flag.workspace = true
dropshot.workspace = true
itertools.workspace = true
migration.workspace = true
sea-orm.workspace = true
secrecy.workspace = true
slog.workspace = true
slog-term.workspace = true
slog-async.workspace = true
spookey.workspace = true
tokio.workspace = true
windows-acls.workspace = true
workspace-hack.workspace = true
