[project]
name = "hipcheck-sdk"
version = "0.2.1"
description = "An SDK for developing Hipcheck plugins"
readme = "README.md"
authors = [
    { name = "j-lanson", email = "jlanson@mitre.org" }
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
license = "Apache-2.0"
license-files = ["LICENSE"]

dependencies = [
    "asyncio>=3.4.3",
    "coverage>=7.6.12",
    "datamodel-code-generator>=0.28.5",
    "grpcio>=1.70.0",
    "grpcio-tools>=1.70.0",
    "logging>=0.4.9.6",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "sphinx>=8.1.3",
    "wheel>=0.45.1",
]

[project.urls]
Homepage = "https://hipcheck.mitre.org/"
Documentation = "https://hipcheck.mitre.org/sdk/python/hipcheck_sdk.html"
Repository = "https://github.com/mitre/hipcheck.git"
Issues = "https://github.com/mitre/hipcheck/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
