[package]
name = "hipcheck-sdk-macros"
description = "Helper macros for the `hipcheck-sdk` crate."
repository = "https://github.com/mitre/hipcheck"
version = "0.2.1"
edition = "2024"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
convert_case = { workspace = true }
tracing = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "printing"] }
hipcheck-workspace-hack = { workspace = true }
