[package]
name = "hipcheck-sdk-macros"
description = "Helper macros for the `hipcheck-sdk` crate."
repository = "https://github.com/mitre/hipcheck"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.7.1"
tracing = "0.1"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "printing"] }
hipcheck-workspace-hack = { version = "0.1", path = "../hipcheck-workspace-hack" }
