//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "cve_list_record_staging")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub generation: i64,
	#[sea_orm(primary_key, auto_increment = false)]
	pub cve_id: String,
	pub record_format_version: String,
	#[sea_orm(column_type = "JsonBinary")]
	pub record: Json,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
