//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "package_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub source_id: String,
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub file_contents: String,
    pub inferred_type: String,
    pub resolution_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
