//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "package_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub source_id: String,
    pub display_name: String,
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub file_contents: String,
    pub inferred_type: String,
    pub resolution_status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub attempt_generation: i32,
    pub cancellation_requested: bool,
    pub terminal_at: Option<DateTimeWithTimeZone>,
    pub deletion_reason: Option<String>,
    pub next_attempt_at: DateTimeWithTimeZone,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub failure_kind: Option<String>,
    pub retryable: bool,
    pub automatic_attempt_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
