//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "public",
    table_name = "upgrade_assessment_verdict_evidence"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub verdict_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub evidence_source_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
