//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "upgrade_assessment_candidates")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub upgrade_assessment_id: String,
	pub candidate_package_version_id: Option<i32>,
	pub candidate_version: String,
	pub upgrade_distance: String,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
