//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
	schema_name = "public",
	table_name = "upgrade_assessment_evidence_sources"
)]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub upgrade_assessment_id: String,
	pub kind: String,
	pub cve_id: Option<String>,
	pub reference: Option<String>,
	#[sea_orm(column_type = "Text", nullable)]
	pub summary: Option<String>,
	#[sea_orm(column_type = "JsonBinary", nullable)]
	pub raw_payload: Option<Json>,
	pub captured_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
