schema-version = "1.11.0"

[install]

## Version Control Software (VCS's)

# Even though Git is required to clone this repo in the first place, we
# choose to include it in the Flox environment because we can't be sure
# that everyone contributing will be on a good recent version of Git out
# of the box.
git = { pkg-path = "git" }
jujutsu = { pkg-path = "jujutsu" }

## Rust Toolchain

rustup = { pkg-path = "rustup" }
cargo-autoinherit = { pkg-path = "cargo-autoinherit" }
cargo-nextest = { pkg-path = "cargo-nextest" }
cargo-hakari = { pkg-path = "cargo-hakari" }
cargo-outdated = { pkg-path = "cargo-outdated" }
cargo-udeps = { pkg-path = "cargo-udeps" }
cargo-audit = { pkg-path = "cargo-audit" }

## Other Backend Tools

# Used to visualize unit-graphs by 'xtask' (provided the `dot` CLI)
graphviz = { pkg-path = "graphviz" }

## Frontend Tools

pnpm = { pkg-path = "pnpm" }

## Database Stuff

postgresql_18 = { pkg-path = "postgresql_18" }
sea-orm-cli = { pkg-path = "sea-orm-cli" }
pgadmin4 = { pkg-path = "pgadmin4" }
