
[dist]

# Make sure that 'dist' will handle releases for this. Otherwise, since
# the crate is set to 'publish = false', 'dist' would ignore it by default.
dist = true

# The installers to generate for each app
installers = ["shell", "powershell"]

# Whether to install an updater program
install-updater = true

# Make sure to include the configuration.
include = ["../config/"]

# Make sure that both Hipcheck and all the plugins are built with the protobuf
# compiler present on their platform.

[dist.dependencies.apt]
protobuf-compiler = "*"

[dist.dependencies.homebrew]
protobuf = "*"

[dist.dependencies.chocolatey]
protoc = "*"
