[workspace]
resolver = "3"
members = ["nv-server", "nv-server-api", "nvdb", "spookey", "workspace-hack", "xtask"]
default-members = ["nv-server"]

[workspace.dependencies]
anyhow = "1.0.102"
camino = "1.2.2"
clap = { version = "4.6.1", features = ["string"] }
dropshot = "0.17.0"
itertools = "0.14.0"
nv-server-api = { path = "nv-server-api" }
sea-orm = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
# This an outdated version, required to match the one expected by dropshot.
# See: https://github.com/oxidecomputer/dropshot/issues/1375
schemars = "0.8.22"
serde = { version = "1.0.228", features = ["derive"] }
# This needs to be compatible with the version used by dropshot.
# See: https://github.com/oxidecomputer/dropshot/issues/1607
slog = "2.8.2"
spookey = { path = "spookey" }
xshell = "0.2.7"
which = "8.0.2"
workspace-hack = { path = "workspace-hack" }
cargo-manifest = "0.21.0"
pathbuf = "1.0.0"

[workspace.dependencies.tokio]
version = "1.52.1"
# TODO: Audit these features to see if we can make this list smaller.
features = [
    "fs", "io-util", "io-std", "net", "parking_lot", "process", "rt", "rt-multi-thread",
    "signal", "sync", "time"
]

[workspace.metadata.cargo-autoinherit]
# Make sure autoinherit doesn't include the workspace-hack crate, since that crate technically
# pulls in a bunch of transitive deps we don't want to unecessarily turn into direct deps.
exclude-members = ["workspace-hack"]
