[package]
name = "hipcheck-macros"
description = "Helper macros for the `hipcheck` crate."
repository = "https://github.com/mitre/hipcheck"
version = "0.3.5"
edition = "2024"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
hipcheck-workspace-hack = { workspace = true }
