[package]
name = "hipcheck-macros"
description = "Helper macros for the `hipcheck` crate."
repository = "https://github.com/mitre/hipcheck"
version = "0.3.5"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
hipcheck-workspace-hack = { version = "0.1", path = "../hipcheck-workspace-hack" }
