name: Docker

# Run once a week on Monday at midnight.
on:
  schedule:
    - cron: "0 0 * * 1"

# This only tries to build the Containerfile, and does not push
# the resulting image to Docker Hub.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          file: dist/Containerfile
          push: false
