name: Docker

# Run once a week on Monday at midnight.
on:
  schedule:
    - cron: "0 0 * * 1"

# This only tries to build the Containerfile, and does not push
# the resulting image to Docker Hub.
jobs:
  build:
    name: "Build Containerfile"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          file: dist/Containerfile
          push: false
