name: Hipcheck

# Run on PRs before merging. We disallow pushing directly to main
# without going through a PR, so we don't run on `push` events for main.
on:
  pull_request:
    branches: [main]
    paths:
      - "config/**"
      - "hipcheck/**"
      - "scripts/**"
      - "xtask/**"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - name: Dependency Tree
        run: cargo tree
      - name: Build
        run: cargo build --verbose --workspace
      - name: Test
        run: cargo test --verbose --workspace
      - name: Lint
        run: cargo clippy --verbose --workspace
