name: Release Dry Run

# Run once a week on Monday at midnight.
on:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      # Get the repo, get Rust, get `cargo-nextest`, setup caching.
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      # Install the protobuf compiler
      - if: runner.os == 'Linux'
        run: sudo apt-get install -y protobuf-compiler
      - if: runner.os == 'macOS'
        run: brew install protobuf
      - if: runner.os == 'Windows'
        run: choco install protoc

      # Print dependency info (useful for debugging)
      - name: Dependency Tree
        run: cargo tree

      # Try building as-if for publishing a new version.
      - name: Publish
        run: cargo publish --dry-run --allow-dirty --verbose -p hipcheck
