name: CI

on:
  push:
    branches: [main]
    paths:
      - "config/**"
      - "hipcheck/**"
      - "scripts/**"
      - "xtask/**"
  pull_request:
    branches: [main]
    paths:
      - "config/**"
      - "hipcheck/**"
      - "scripts/**"
      - "xtask/**"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependency Tree
        run: cargo tree
      - name: Build
        run: cargo build --verbose --workspace
      - name: Test
        run: cargo test --verbose --workspace
      - name: Lint
        run: cargo clippy --verbose --workspace
