[package]
name = "nvdb"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
nv-common.workspace = true
sea-orm.workspace = true
secrecy.workspace = true
url.workspace = true
workspace-hack.workspace = true
